markdown:           redcarpet
redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

permalink:           pretty

# Setup
title:               Steve-254 Blog
tagline:             The Tech Enthusiasts Pool
description:         ''
home:		             http://steve-254.github.io/
url:                 http://steve-254.github.io/blog/
baseurl:             /blog/
paginate:            5
paginate_path:       "/page:num/"
exclude:             ['posts']

# About/contact
author:
name:              Steve 254
url:               http://steve-254.github.io
email:             primary.stephen@gmail.com

# Custom vars
version:             1.0.0

## This is the list of pages to include in the header of the website.
pages_list:       
  About: '/blog/about'
  Atom: '/blog/atom.xml'
  RSS: '/blog/rss.xml'